### ISSUE TITLE
Poms 2.0

### ISSUE THREAD

**Issue by rpbaptist** [brightin/poms#37]
# Poms 2.0

Poms is beign rewritten to address the Poms frontend API. The Poms gem will retrieve media information as described on the [NPO Wiki](http://wiki.publiekeomroep.nl/display/npoapi/Media-+en+gids-API).

Steps required to accomplish this:

- [x] Address the correct API and namespace in expected format
- [x] Send parameters as specified by NPO
- [x] Make Poms gem configurable with credentials
- [x] Implement authentication as specified by NPO
- [x] Use the Poms gem only as an API interface and maintain business logic in applications Zapp and Zappelin only
- [x] Allow for specific search params such as media type, starting and end times, etc to be set in the body.
- [x] Cover all scenario's as currently used in Zapp (Zappelin will follow later)
- [x] After Poms gem has been updated and meets these requirements, use version 2.0.0 in Zapp and rewrite the PomsImporter to use the new format

**Comment by rpbaptist** [comment]
## Zapp use cases


Poms should be able to retrieve the following information:

- [x] Retrieve upcoming episodes (two weeks) for a serie
- [x] Retrieve all episodes for a serie
- [ ] Serie general information
- [ ] Retrieve all segments for an episodes
- [ ] Episode specific information

**Comment by yannvanhalewyn** [comment]
:+1:

**Comment by rpbaptist** [comment]
What the new code could look like in Zapp:

(Existing method names used)

```ruby
PomsImporter.import_upcoming_broadcasts_for_serie(serie)
  Poms.descendants(
    serie.mid,
    starts_on: Time.zone.now,
    ends_on: 2.weeks.from_now,
    type: 'BROADCAST'
  )
end
```

There will be no need to first fetch descendent mids and then call `Poms.fetch` on each of those mids. This call should return all the episode objects.

**Comment by rpbaptist** [comment]
`Poms.configure {}` should be called with the scheme and host.

Verify this on start of Poms gem. (end of `Poms.configure` method)

**Comment by tomkr** [comment]
One problem we do have now is that by default only 10 items are fetched, that should either be more or we should paginate. Probably both actually.

**Comment by tomkr** [comment]
Another problem with the current code is that it doesn't support Ruby 1.9.3, which Zappelin is still running in.

**Comment by rpbaptist** [comment]
I think the problem isn't that this code doesn't support Ruby 1.9.3. I think the problem is that Zappelin is still running on 1.9.3 and we should urge it forward.

**Comment by tomkr** [comment]
@rpbaptist And I know which one I can influence within this project.

**Comment by rpbaptist** [comment]
Who is urging us to move Zappelin to Poms 2.0?

**Comment by rpbaptist** [comment]
maximum aantal resultaten: Code implementeren en wellicht default omhoog zetten. (Dat is momenteel slechts 10)

**Comment by yannvanhalewyn** [comment]
I agree with @rpbaptist on this one. We could really use this to catalyze the Ruby update process in Zappelin. 
Also, I feel like we shouldn't be maintaining such old ruby versions, leave alone writing entirely new code in it.

**Comment by tomkr** [comment]
Note the master branch is 2.0 now, so PRs can be made on master.

I'd love to be able to agree, but it was a tiny change and it allowed to unblock my other work, so I took the pragmatic step here. I'm totally fine with reverting the change and using Ruby 2.0+ or even just 2.3 syntax when we release this to Rubygems. With this change documented in the Readme, preferably.

**Comment by tomkr** [comment]
2.0 has been released, so I'm closing this.
