### ISSUE TITLE
Missing Gemfile.lock

### ISSUE THREAD

**Issue by avdgaag** [brightin/poms#8]
The Gemfile.lock should probably be checked into source control to indicate the exact version of dependencies required.

**Comment by tomkr** [comment]
Interesting point. Gemfile.lock is apparently listed in the gitignore, but could there have been a good reason to do that?

**Comment by avdgaag** [comment]
Maybe as a stand-alone gem it makes fewer sense than to rely on the gemspec itself?

**Comment by tomkr** [comment]
As per http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ I'm going to close this issue.

**Comment by hamaker** [comment]
Hey there, long time no see! Actually, starting a gem through `bundle gem` (as I did for poms) initialises a repo and puts the Gemfile.lock in the .gitignore, that was the 'good reason' to put it in there when I started the poms gem, which implies a best practice, I guess.

**Comment by tomkr** [comment]
I figured you'd have your reasons, Niels. :-D
