### ISSUE TITLE
Fix check for odi_streams

### ISSUE THREAD

**Issue by verberktstan** [brightin/poms#90]
https://github.com/brightin/poms/blob/3867b2a1c7f848a8f38aec487f240126922ab3d6/lib/poms/fields.rb#L63

The regexp match does not always match the right odi streams. I think we could remove the Regexp matcher because then the check would work. (i've found occurances where there is actually an INTERNETVOD stream noted in poms, but it isn't returned in this function)

**Comment by tomkr** [comment]
@verberktstan Do you have an example so we can produce a failing test case and fix it from there?
